name: Deploy to Cloud Run

on:
  push:
    branches:
      - main  # Atau cabang lain yang ingin kamu gunakan

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: 'latest'
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Authenticate to Google Cloud
        run: gcloud auth activate-service-account --key-file=${{ secrets.GCP_SA_KEY }}

      - name: Configure Docker
        run: gcloud auth configure-docker

      - name: Build Docker image
        run: |
          docker build -t gcr.io/YOUR_PROJECT_ID/YOUR_IMAGE_NAME:$GITHUB_SHA .
          docker push gcr.io/YOUR_PROJECT_ID/YOUR_IMAGE_NAME:$GITHUB_SHA

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy YOUR_SERVICE_NAME \
            --image gcr.io/YOUR_PROJECT_ID/YOUR_IMAGE_NAME:$GITHUB_SHA \
            --platform managed \
            --region YOUR_REGION \
            --allow-unauthenticated
